config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :emails
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'emails#index'

  get '/email/test', to: 'emails#test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: %i[ show edit update destroy ]

  # GET /emails or /emails.json
  def index
    @emails = Email.order(read: :asc, created_at: :desc)
    @count = Email.count
  end
  

  # GET /emails/1 or /emails/1.json
  def show
    @email.update(read: true)
  end

  # GET /emails/new
  def new
    @email = Email.new
  end

  # GET /emails/1/edit
  def edit
  end

  def test
  end

  # POST /emails or /emails.json
  def create
    @email = Email.new(object: Faker::Lorem.sentence,
      body: Faker::Lorem.paragraphs(number: 3).join("\n"), read: false)

      
      if @email.save
        puts "email is success"
        refresh_emails
      else
        puts "email is failed"
      end

  end

  # PATCH/PUT /emails/1 or /emails/1.json
  def update
      if @email.update(email_params)
        render :show
      else
        render :edit
      end
    end

  # DELETE /emails/1 or /emails/1.json
  def destroy
    @email.destroy
    redirect_to emails_path, notice: 'Email supprimé !'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def refresh_emails
      render turbo_stream: [
              turbo_stream.update("email_counter", Email.count),
              turbo_stream.prepend("refresh_email",
                                  partial: "emailsindex",
                                  locals: { email: @email})]
                  
    end


    def refresh_read_emails
      render turbo_stream:
        turbo_stream.update("refresh_email",
                          partial: "emailsindex",
                          locals: { email: @email})
    end

    def remove_email
      render turbo_stream:[
              turbo_stream.remove(@email),
              turbo_stream.update("email_counter", Email.count),
            ]
    end



    def set_email
      @email = Email.find(params[:id])
      @count = Email.count
    end

   
    # Only allow a list of trusted parameters through.
    def email_params
      params.require(:email).permit(:object, :body)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.order(created_at: :desc)
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
    respond_to do |format|
      format.turbo_stream do 
        render turbo_stream: turbo_stream.update(@message,
                                                 partial: "messages/form",
                                                 locals: {message: @message})
      end
    end
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update('new_message',
                                partial: "messages/form",
                                locals: {message: Message.new}),
            turbo_stream.prepend('messages',
                                partial: "messages/message",
                                locals: {message: @message}),
            turbo_stream.update('message_counter', Message.count),
            turbo_stream.update('notice', "Message #{@message.id} created")
            # turbo_stream.update('message_counter', html: Message.count)
            # turbo_stream.update('message_counter', html: "#{Message.count}")
            # turbo_stream.append('messages',
            #                     partial: "messages/message",
            #                     locals: {message: @message})
            ]
        end
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update('new_message',
                                partial: "messages/form",
                                locals: {message: @message})
            ]
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.turbo_stream do 
          render turbo_stream: [
            turbo_stream.update(@message,
                                partial: "messages/message",
                                locals: {message: @message}),
            turbo_stream.update('notice', "Message #{@message.id} updated")
          ]
        end
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.turbo_stream do 
          render turbo_stream: turbo_stream.update(@message,
                                                   partial: "messages/form",
                                                   locals: {message: @message})
        end
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@message),
          turbo_stream.update('message_counter', Message.count),
          turbo_stream.update('notice', "Message #{@message.id} deleted")
          ]
      end
      # format.turbo_stream { render turbo_stream: turbo_stream.remove("message_#{@message.id}") }
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GmailHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>" class="scaffold_record">
  <p>
    <strong>Body:</strong>
    <%= message.body %>
  </p>

  <p>
    <%= link_to "Show this message", message %>
    <%= button_to "Edit this message", edit_message_path(message), method: :post %>
    <%= button_to "Destroy this message", message_path(message), method: :delete %>
  </p>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<h1>
  Messages
  <span id="message_counter">
    <%= Message.count %>
  </span>
</h1>

<div id="new_message">
  <%= render partial: "messages/form", locals: { message: Message.new } %>
</div>

<div id="messages">
  <%= render @messages %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>